---

# a tasks file to install basic packages for development
- name: ubuntu-based basic packages install
  block:
    - name: Install basic packages via apt module
      apt:
        name: "{{ apt_pkgs }}"
        state: latest
        update_cache: yes
      become: yes

    - name: Install debug packages if in debug mode
      apt:
        name:
            - neovim
            - wget
            - tree
            - fzf
            - silversearcher-ag
            - ripgrep
            - tmux
            - fd-find
        state: latest
      become: yes
      when: debug_mode
  when: ansible_os_family == "Debian"

# a tasks file to install basic packages for development
- name: arch-based basic packages install
  block:
    - name: Install basic packages via apt module
      pacman:
        name: "{{ pacman_pkgs }}"
        state: latest
        update_cache: yes
      become: yes
  when: ansible_os_family == "Archlinux"

