---

# a tasks file to install basic packages for development
- name: ubuntu-based basic packages install
  block:
    - name: Install basic packages via apt module
      apt:
        name:
          - git
          - curl
          - python3
          - python3-pip
          - zoxide
          - tree
        state: latest
        update_cache: yes
      become: yes

    - name: Install basic packages via apt module (in docker)
      apt:
        name:
          - nodejs
          - npm
          - tmux
          - ripgrep
          - fd-find
        state: latest
      become: yes
      when: ansible_facts.is_docker | default(false)

    - name: Install debug packages if in debug mode
      apt:
        name:
            - neovim
            - wget
            - tree
            - fzf
            - silversearcher-ag
            - ripgrep
            - tmux
            - fd-find
        state: latest
      become: yes
      when: debug_mode
  when: ansible_os_family == "Debian"

# a tasks file to install basic packages for development
- name: ubuntu-based basic packages install
  block:
    - name: Install basic packages via apt module
      pacman:
        name:
          - git
          - curl
          - python3
          - python3-pip
          - zoxide
          - tree
          - nodejs
          - npm
          - tmux
          - ripgrep
          - fd-find
          - neovim
          - wget
          - tree
          - fzf
          - silversearcher-ag
        state: latest
        update_cache: yes
      become: yes
  when: ansible_os_family == "Archlinux"
