live_config_reload = false

[bell]
animation = "Linear"
color = "#b59b9c"
duration = 500

[cursor.style]
blinking = "On"
shape = "Block"

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

# [line_indicator]
# background = "#b59b9c"
# foreground = "#b59b9c"

[scrolling]
multiplier = 15

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[window]
decorations = "transparent"
dynamic_padding = false
dynamic_title = false
opacity = 0.9
startup_mode = "Windowed"

[window.dimensions]
columns = 150
lines = 45

[window.padding]
x = 0
y = 0

[window.position]
x = 2500
y = 700
