---
- name: pCheck if Hack.zip is available
  stat:
    path: "{{ tmp_dir }}/Hack.zip"
  register: hack_file

# tasks file for nerdfont
- name: Download Hack font fro nerd fonts repo
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Hack.zip"
    dest: "{{ tmp_dir }}/Hack.zip"
  become: yes
  when: hack_file.stat.exists

    # - name: Check if Hack.zip is available
    #   stat:
    #     path: "{{ tmp_dir }}/Hack.zip"
    #   register: hack_file.stat.exists

- name: Install Hack Nerd Font
  shell: |
    mkdir -p {{ ansible_env.HOME }}/.local/share/fonts && unzip -f {{ tmp_dir }}/Hack.zip
  when: hack_file.stat.exists


