---
- name: Check if FiraCode.zip is available
  stat:
    path: "{{ tmp_dir }}/FiraCode.zip"
  register: hack_file

# tasks file for nerdfont
- name: Download Hack font from nerd fonts repo
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FiraCode.zip
    dest: "{{ tmp_dir }}/FiraCode.zip"
  become: yes
  when: not hack_file.stat.exists

    # url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip"
  # https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FiraCode.zip
  
    # - name: Check if Hack.zip is available
    #   stat:
    #     path: "{{ tmp_dir }}/Hack.zip"
    #   register: hack_file.stat.exists

- name: Check if FiraCode.zip is available
  stat:
    path: "{{ tmp_dir }}/FiraCode.zip"
  register: hack_file

- name: Install Hack Nerd Font
  shell: |
    mkdir -p {{ ansible_env.HOME }}/.local/share/fonts
    unzip -o {{ tmp_dir }}/FiraCode.zip -d {{ ansible_env.HOME }}/.local/share/fonts/
  when: hack_file.stat.exists
    # creates: "{{ ansible_env.HOME }}/.local/share/fonts/HackNerdFont-Regular.ttf"

- name: Update font cache
  shell: |
    fc-cache
  become: yes
  when: hack_file.stat.exists
