---
galaxy_info:
  author: "Iuro Nascimento"
  description: "Ansible role to stow configuration dotfiles"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Linux
      versions:
        - "Ubuntu 24.04"
        - "LinuxMint 22.1"
dependencies:
  - role: node
  - role: stow
    # vars:
    #   some_variable: value
