---
- name: Check if stow is available
  ansible.builtin.stat:
    path: /usr/local/bin/stow
  register: stow_check

- name: Use script to symlink configuration files from repo to system
  shell: |
   "{{ home_dir }}/git/dotfiles/bin/setup.sh"
  when: stow_check.stat.exists
  args:
    executable: /bin/bash
  # become: true
  # become_user: "{{ ansible_env.USER }}"
