---
- name: Install system packages
  apt:
    name: "{{ apt_packages }}"
    state: latest
    update_cache: true
  # when: ansible_facts.ansible_pkg_mgr == "apt"
  become: yes

# - name: Install system packages
#   pacman:
#     name: {{ pacman_packages }}
#     state: latest
#     update_cache: true
#   when: ansible_facts.ansible_pkg_mgr == "apt"

- name: Add Neovim nightly PPA
  apt_repository:
    repo: ppa:neovim-ppa/stable
    codename: noble
    state: present
  become: yes
  # when: ansible_facts.ansible_pkg_mgr == "apt"

- name: Install Neovim
  apt:
    name: 
    - neovim
    state: latest
    update_cache: yes
  become: yes
  # when: ansible_facts.ansible_pkg_mgr == "apt"

# - name: Install Neovim
#   pacman:
#     name: 
#     - neovim
#   when: ansible_facts.ansible_pkg_mgr == "pacman"

- name: Include node provider task
  include_tasks: node-provider.yml

- name: Include ruby provider task
  include_tasks: ruby-provider.yml

- name: Include python provider task
  include_tasks: python-provider.yml

- name: Include perl provider task
  include_tasks: perl-provider.yml 
