---
- name: Install Node.js Neovim provider on Debian-based systems
  shell: |
    . .nvm/nvm.sh
    nvm use 22
    npm -g install neovim
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
  when: ansible_os_family == "Debian"

- name: Install Node.js Neovim provider on Archlinux
  shell: |
    npm -g install neovim
  args:
    executable: /bin/bash
  become: yes
  when: ansible_os_family == "Archlinux"
