# This playbook installs the python provider for ansible
- name: Install python packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - virtualenv
    state: latest
    update_cache: true
  become: yes

# create a virtualenv for python3
- name: Create virtualenv for python3
  shell: |
    virtualenv {{ base_env }}
  args:
    chdir: "{{ home_dir }}"
    creates: "{{ base_env }}/bin/activate"

- name: Check if base_env is created
  stat:
    path: "{{ base_env }}/bin/activate"
  register: venv_activate

- name: Install neovim package in virtual environment
  shell: |
    bash -c ". {{ base_env }}/bin/activate && pip install neovim"
  args:
    executable: /bin/bash
  when: venv_activate.stat.exists

