---
- name: Ensure Ruby is installed
  apt:
    name: 
      - ruby
      - gem
    state: latest
    update_cache: yes
  become: yes

- name: Install Ruby Neovim provider
  gem:
    name: neovim
    state: latest
    user_install: no
  become: yes

