---
galaxy_info:
  author: "Iuro Nascimento"
  description: "Installs neovim and providers for various languages"
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - "20.04"
        - "24.04"
    - name: LinuxMint
      versions:
        - "22.1"
dependencies: 
  - role: node
