---
pacman_packages:
  - python
  - python-pip
  - virtualenv
  - ruby
  - base-devel
  - curl
  - perl
  - cpanminus
  - gnupg
  - nodejs
  - npm
  - xclip
  - xsel
apt_packages:
  - python3
  - python3-pip
  - virtualenv
  - python-is-python3
  - ruby
  - ruby-dev
  - build-essential
  - curl
  - perl
  - cpanminus
  - gnupg2
  - nodejs
  - npm
  - xclip
  - xsel
base_env: "{{ ansible_facts.ansible_env.HOME }}/.env/base"
