---
- name: "Install luarocks dependencies"
  apt:
    name:
      - build-essential
      - libreadline-dev
      - unzip
      - libsqlite3-dev
    state: latest
    update_cache: true
  become: yes
  when: ansible_os_family == "Debian"

- name: "Install luarocks dependencies"
  pacman:
    name:
        - base-devel
        - unzip
        - sqlite
    state: latest
    update_cache: true
  become: yes
  when: ansible_os_family == "Archlinux"

# Compile and install Luarocks
- name: Download Luarocks source
  get_url:
    url: "https://luarocks.github.io/luarocks/releases/luarocks-{{ luarocks_version }}.tar.gz"
    dest: "{{ tmp_dir }}/luarocks-{{ luarocks_version }}.tar.gz"
  become: yes

- name: Extract Luarocks source
  unarchive:
    src: "{{ tmp_dir }}/luarocks-{{ luarocks_version }}.tar.gz"
    dest: "{{ tmp_dir }}"
    remote_src: yes
  become: yes

- name: Compile and install Luarocks
  shell: |
    ./configure --with-lua-include=/usr/local/include
    make
    make install
  args:
    creates: "/usr/local/bin/luarocks"  # Adjust if needed
    chdir: "{{ tmp_dir }}/luarocks-{{ luarocks_version }}"
  become: yes

- name: Install some rocks
  shell: |
    luarocks install {{ item }}
  loop: "{{ rocks }}"
  become: yes
