---
galaxy_info:
  author: "Iuro Nascimento"
  description: "Ansible role to install luajit"
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Linux
      versions:
        - "Ubuntu 24.04"
        - "LinuxMint 22.1"

