---
# Default variables for Perl and Neovim::Ext installation

# Packages to install via apt
perl_packages:
  - perl
  - cpanminus

# CPAN module to install
cpan_module: "Neovim::Ext"

home_dir: "{{ ansible_env.HOME }}"
