---
fish_plugins:
  - jorgebucaran/spark.fish
  - gazorby/fish-abbreviation-tips
  - jethrokuan/z
  - jomik/fish-gruvbox
  - sujaybokil/fish-gruvbox
  - edc/bass
  - wfxr/forgit
  - jorgebucaran/nvm.fish
  - ilancosman/tide
home_dir: "{{ ansible_env.HOME }}"
