# Dark Gruvbox Color Scheme for Taskwarrior
# color 0      dark black
# color 1      dark red
# color 2      dark green
# color 3      dark yellow
# color 4      dark blue
# color 5      dark purple
# color 6      neutral green(cyan?)
# color 7      dark white(light grey)
# color 8      light black(dark grey)
# color 9      light red
# color 10     light green
# color 11     light yellow
# color 12     light blue
# color 13     light purple
# color 14     light cyan
# color 15     light white

rule.precedence.color=deleted,completed,active,keyword.,tag.,project.,overdue,scheduled,due.today,due,blocked,blocking,recurring,tagged,uda.
# general decoration
color.label=color7
color.label.sort=color7
color.alternate=on color0 #color0

color.header=bold color15 on color0       # Bold color15 on color0
# color.footnote=bold color15 on color0     # Bold color15 on color0
color.warning=color0 on color11
color.error=color0 on color9
color.debug=color13


color.summary.background=color15 on gray3         # color0 background
color.summary.bar=black on color4         # color15 text

# Task attributes
color.completed=bold color15             # color15
color.deleted=bold color1                 # Red
color.active=bold color4 on color15 # on white                 # Cyan
# color.active=bold color12 # on white                 # Cyan
color.recurring=bold color6            # Yellow
color.scheduled=
# color.until=
color.blocked=color13 # light purple
color.blocking=color3 #color15 #on color10

# color.project.name=bold color12 #on yellow
# color.project.none=bold color15 #on yellow

color.tag.next=bold color13
color.tag.none=
color.tagged=color4                  # Green

# color.due=bold red                     # Red
color.uda.priority.H=bold color9            # Red
color.uda.priority.M=bold color11       # Yellow
color.uda.priority.L=color7           # Green

#project
# x color.project=bold blue                # Blue

# # Overdue tasks
color.overdue=bold color9 on color0        # Red on color0
color.due=color15
color.due.today=bold color11

# Report: burndown
color.burndown.done=color0 on color6
color.burndown.pending=color0 on color1
color.burndown.started=color0 on color3

# Report: history
color.history.add=color0 on color1
color.history.delete=color0 on color3
color.history.done=color0 on color6

# Calendar colors
color.calendar.due=bold color12 on color0            # Red on color0
color.calendar.due.today=bold color11 on gray9       # Red on cyan
color.calendar.overdue=bold color9 on color0        # Red on color0
color.calendar.holiday=bold yellow on color0     # Yellow on color0
color.calendar.scheduled=
color.calendar.today=bold color13 on gray9         # Cyan on color0
color.calendar.weekend=bold magenta on color0    # Magenta on color0
color.calendar.weeknumber=bold color15 on color0   # color15 on color0
# color.calendar.recurring=bold color14 # on color0   # color15 on color0

# color.calendar.header=bold color14 on color0       # Bold color15 on color0


# Command: sync
color.sync.added=color14
color.sync.changed=color9
color.sync.rejected=color13

# # Command: undo
# color.undo.after=color2
# color.undo.before=color1



color.footnote=color3


