#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/rocks
- name: Install dependencies of luarocks target packages
  apt:
    name:
      - libssl-dev
      - libsqlite3-dev
      - git
    state: latest
  become: yes

- name: Install Lua packages from rockspec
  shell: |
    bash -c 'sudo luarocks install --deps-only "{{ lua_rockspec_path }}"'
  become: yes

  # args:
  #   chdir: "{{ lua_rockspec_dir }}"
  # environment:
  #   PATH: "{{ home_dir }}/.luarocks/bin:{{ ansible_env.PATH }}"

