---
- hosts: 
    - local
  gather_facts: true
  vars:
    debug_mode: false
    tasks_dir: "tasks"
    home_dir: "{{ ansible_env.HOME }}"

  roles:
    - base
    - fzf
    - rust
    - nerdfont
    - lua
    - luajit
    - neovim
    # - luarocks
    # - keepass
    - stow
    - dotfiles

