---
- hosts: 
    - local
  gather_facts: true
  vars:
    debug_mode: false
    tasks_dir: "tasks"
    home_dir: "{{ ansible_env.HOME }}"

  roles:
    - stow-dotfiles
    - base
    - ghostty
    - nerdfont
    - fzf
    - lua
    - luajit
    - neovim
    - luarocks
    - rustup
    - role: fish
      vars:
        fish_plugins:
          - jorgebucaran/nvm.fish
          - ilancosman/tide@v6
          - edc/bass
          - patrickf1/fzf.fish
          - jorgebucaran/autopair.fish
          - nickeb96/puffer-fish
          - gazorby/fish-abbreviation-tips
          - brgmnn/fish-docker-compose
          - patrickf1/colored_man_pages.fish
    - keepass
    - rocks

