---
# - hosts: 
#     - local
#   become: yes
#   roles:
#
#     - luapath
    # - rustup
    # - rust-pkgs

- name: Run additional tasks after roles
  hosts: 
    - local
  become: yes
  tasks:
    - name: Extra configuration task
      shell: |
        "{{ ansible_env.HOME }}/git/dotfiles/bin/setup.sh"
      args:
        chdir: "{{ ansible_env.HOME }}/git/dotfiles"

