---
# Default variables for installing Rust and Cargo packages

# URL for the rustup installation script.
rustup_install_script_url: "https://sh.rustup.rs"

# A list of Cargo packages to install.
# Adjust these to the packages you need; you can also specify versions (e.g., "ripgrep@13.0.0")
cargo_packages:
  - ripgrep
  - bat
  - fd-find


# Additional flags for cargo install (for example, to use a lock file).
cargo_install_flags: ""
