---
# Compile and install Lua
- name: Download Lua source
  get_url:
    url: "https://www.lua.org/ftp/lua-{{ lua_version }}.tar.gz"
    dest: "{{ tmp_dir }}/lua-{{ lua_version }}.tar.gz"

- name: Extract Lua source
  unarchive:
    src: "{{ tmp_dir }}/lua-{{ lua_version }}.tar.gz"
    dest: "{{ tmp_dir }}"
    remote_src: yes

- name: Install lua dependencies
  apt: 
    name: 
      - build-essential 
      - libreadline-dev
      - unzip
    state: latest
    update_cache: true
  become: yes

- name: Compile and install Lua
  shell: |
    cd {{ tmp_dir }}/lua-{{ lua_version }} && make linux && make install
  args:
    creates: "/usr/local/bin/lua"  # Adjust if needed
  become: yes

