---
# Compile and install Lua

- name: Dompile and install lua
  block:
    - name: Download Lua source
      get_url:
        url: "https://www.lua.org/ftp/lua-{{ lua_version }}.tar.gz"
        dest: "{{ tmp_dir }}/lua-{{ lua_version }}.tar.gz"

    - name: Extract Lua source
      unarchive:
        src: "{{ tmp_dir }}/lua-{{ lua_version }}.tar.gz"
        dest: "{{ tmp_dir }}"
        remote_src: yes

    - name: Install lua dependencies
      apt: 
        name: 
          - build-essential 
          - libreadline-dev
          - unzip
        state: latest
        update_cache: true
      become: yes

    - name: Compile and install Lua
      shell: |
        cd {{ tmp_dir }}/lua-{{ lua_version }} && make linux && sudo make install
      args:
        creates: "/usr/local/bin/lua"  # Adjust if needed
      become: yes
  when: ansible_distribution == "Debian"

- name: Install lua 5.1
  pacman: 
    name: 
      - lua
      - lua51
    state: latest
    update_cache: true
  become: yes
  when: ansible_distribution == "Archlinux"


